### ISSUE TITLE
Failed to pull docker://cmatkhan/pycallingcards:latest 

### ISSUE THREAD

**Issue by allenyen** [nf-core/callingcards#9]
### Description of the bug

I'm trying out the test profile using the `-profile test,singularity` parameter and run into this error when pulling the pycallingcards image. All other preceding images get pulled without any issues. I tried `singularity pull docker://cmatkhan/pycallingcards:latest` in the terminal outside of nextflow and got the same error output. Is the image still public or is it something on my end?

### Command used and terminal output

```console
nextflow run nf-core/callingcards -profile test,singularity -c /ref/jdlab/software/nextflow/wustl_htcf.config --output test_run

Error executing process > 'NFCORE_CALLINGCARDS_MAMMALS:CALLINGCARDS_MAMMALS:PROCESS_ALIGNMENTS:HOPS_MAMMALS (human_AY53-1_50_T1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name cmatkhan-pycallingcards-latest.img.pulling.1691359463025 docker://cmatkhan/pycallingcards:latest > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://cmatkhan/pycallingcards:latest: reading manifest latest in docker.io/cmatkhan/pycallingcards: errors:
    denied: requested access to the resource is denied
    unauthorized: authentication required
```

**Comment by allenyen** [comment]
So anybody running a test profile will need to use the dev branch?

**Comment by cmatKhan** [comment]
until it is officially released, you'll need to use the dev branch.


An explanation: 

the `-r` flag is the version. It will be released, when I get a chance to put time towards this again, hopefully this month, as version 1.0.0. If a user wanted to hold their processing consistent at that version, then they would use `-r 1.0.0`.

If it turns out that there is some feature we want to add to version 1.0.0, then I can add it to the `dev` branch to make it available with `-r dev` until it eventually gets an official release, eg 1.1.0.
